apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::706015325948:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-AWD8Y6THOFFQ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::706015325948:role/UdacityFlaskDeployCBKubectlRole
      username: build  
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-02T19:09:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1443"
  uid: d59011b2-8758-4f81-a793-5e29657b2579
